_wandb:
    value:
        cli_version: 0.23.1
        e:
            1k5hge6tv0z7e9dxv87gi2a6duxlzi6s:
                codePath: src/main.py
                codePathLocal: src/main.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1965728006144"
                        used: "244134092800"
                email: kimmung1999@gmail.com
                executable: /data/ephemeral/home/Chemical_Process_Anomaly_Detection/.venv/bin/python3
                git:
                    commit: bb3e715ae79367fa98a378f3df7d69627d213f3f
                    remote: https://github.com/AIBootcamp14/ai-ad_2.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-c0da5c26-2c86-d498-da0d-22f3fdf9f9de
                host: instance-16981
                memory:
                    total: "270172033024"
                os: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
                program: /data/ephemeral/home/Chemical_Process_Anomaly_Detection/src/main.py
                python: CPython 3.12.12
                root: /data/ephemeral/home/Chemical_Process_Anomaly_Detection
                startedAt: "2025-12-04T04:19:52.298936Z"
                writerId: 1k5hge6tv0z7e9dxv87gi2a6duxlzi6s
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 5
                - 50
                - 53
            "2":
                - 5
                - 50
                - 53
            "3":
                - 2
                - 15
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
eda_only:
    value: false
model:
    value:
        iforest:
            bootstrap: false
            contamination: auto
            max_features: 1
            max_samples: auto
            n_estimators: 200
            n_jobs: -1
model_type:
    value: IFOREST
output_path:
    value: output_hydra.csv
seed:
    value: 42
