# conf/config.yaml

defaults:
  - app_schema
  - model: lstm_ae
  - _self_

# 공통 설정
seed: 42

# 앙상블 결과 제출 파일 이름
output_path: "output_${model_type}.csv"

# 스케일러 설정
preprocess:
  enabled: true
  scaler: "robust"      # "standard" | "robust" | "none"
  with_centering: true
  with_scaling: true
  quantile_range: [25.0, 75.0]
  clip: null              # 예: 10.0

# 어떤 모델 모드를 쓸지
#  - 단일 모델: IFOREST / SGD / LOF / EE / LSTM_AE
#  - 앙상블: ENSEMBLE
model_type: LSTM_AE

# EDA만 돌리고 싶으면 true
eda_only: false

# 앙상블 설정 (model_type: ensemble 일 때만 사용)
# 어떤 서브 모델들을 앙상블에 포함할지
ensemble_models:
  - IFOREST
  - LOF
  - EE
  # - SGD

# Hard voting 임계값
#  - 각 모델 예측(0/1)의 평균이 threshold 이상이면 1(이상), 아니면 0(정상)
ensemble_vote_threshold: 0.5

# wandb 설정
use_wandb: true
wandb_project: "chemical-process-anomaly-detection"
wandb_entity: null

wandb_run_name: "${now:%Y%m%d_%H%M%S}_${model_type}_kmc"

wandb_tags: ["${model_type}"]

hydra:
  job:
    chdir: false
